In [157]:
from pandas_datareader import data, wb
import pandas as pd
import numpy as np
import datetime
import pandas as pd
from sqlalchemy import create_engine, text
import matplotlib.pyplot as plt
import seaborn as sns

In [198]:
df = pd.read_csv('/Users/cdub/Grand Circus/heart_attack_china.csv')
pd.set_option('display.max_columns', None)

In [200]:
df.head()

,Patient_ID,Age,Gender,Smoking_Status,Hypertension,Diabetes,Obesity,Cholesterol_Level,Air_Pollution_Exposure,Physical_Activity,Diet_Score,Stress_Level,Alcohol_Consumption,Family_History_CVD,Healthcare_Access,Rural_or_Urban,Region,Province,Hospital_Availability,TCM_Use,Employment_Status,Education_Level,Income_Level,Blood_Pressure,Chronic_Kidney_Disease,Previous_Heart_Attack,CVD_Risk_Score,Heart_Attack
0,1,55,Male,Non-Smoker,No,No,Yes,Normal,High,High,Moderate,Low,Yes,No,Good,Rural,Eastern,Beijing,Low,Yes,Unemployed,Primary,Low,104,Yes,No,78,No
1,2,66,Female,Smoker,Yes,No,No,Low,Medium,High,Healthy,Medium,No,Yes,Poor,Urban,Eastern,Qinghai,High,No,Unemployed,Secondary,Middle,142,No,No,49,No
2,3,69,Female,Smoker,No,No,No,Low,Medium,High,Moderate,Low,No,No,Poor,Rural,Eastern,Henan,Low,No,Unemployed,Primary,High,176,No,No,31,No
3,4,45,Female,Smoker,No,Yes,No,Normal,Medium,Low,Healthy,Medium,Yes,No,Poor,Rural,Central,Qinghai,Medium,Yes,Employed,Primary,Low,178,No,Yes,23,No
4,5,39,Female,Smoker,No,No,No,Normal,Medium,Medium,Healthy,Low,No,No,Moderate,Urban,Western,Guangdong,Low,No,Retired,Higher,Middle,146,Yes,No,79,No

In [202]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239266 entries, 0 to 239265
Data columns (total 28 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Patient_ID              239266 non-null  int64
 1   Age                     239266 non-null  int64
 2   Gender                  239266 non-null  object
 3   Smoking_Status          239266 non-null  object
 4   Hypertension            239266 non-null  object
 5   Diabetes                239266 non-null  object
 6   Obesity                 239266 non-null  object
 7   Cholesterol_Level       239266 non-null  object
 8   Air_Pollution_Exposure  239266 non-null  object
 9   Physical_Activity       239266 non-null  object
 10  Diet_Score              239266 non-null  object
 11  Stress_Level            239266 non-null  object
 12  Alcohol_Consumption     239266 non-null  object
 13  Family_History_CVD      239266 non-null  object
 14  Healthcare_Access       239266 non-null  object
 15  Rural_or_Urban          239266 non-null  object
 16  Region                  239266 non-null  object
 17  Province                239266 non-null  object
 18  Hospital_Availability   239266 non-null  object
 19  TCM_Use                 239266 non-null  object
 20  Employment_Status       239266 non-null  object
 21  Education_Level         179649 non-null  object
 22  Income_Level            239266 non-null  object
 23  Blood_Pressure          239266 non-null  int64
 24  Chronic_Kidney_Disease  239266 non-null  object
 25  Previous_Heart_Attack   239266 non-null  object
 26  CVD_Risk_Score          239266 non-null  int64
 27  Heart_Attack            239266 non-null  object
dtypes: int64(4), object(24)
memory usage: 51.1+ MB

### Check Null Values

In [223]:
df.isna().sum()

Patient_ID                0
Age                       0
Gender                    0
Smoking_Status            0
Hypertension              0
Diabetes                  0
Obesity                   0
Cholesterol_Level         0
Air_Pollution_Exposure    0
Physical_Activity         0
Diet_Score                0
Stress_Level              0
Alcohol_Consumption       0
Family_History_CVD        0
Healthcare_Access         0
Rural_or_Urban            0
Region                    0
Province                  0
Hospital_Availability     0
TCM_Use                   0
Employment_Status         0
Education_Level           0
Income_Level              0
Blood_Pressure            0
Chronic_Kidney_Disease    0
Previous_Heart_Attack     0
CVD_Risk_Score            0
Heart_Attack              0
dtype: int64

In [217]:
# Find unique values in education level
df['Education_Level'].unique()

array(['Primary', 'Secondary', 'Higher', nan], dtype=object)

In [219]:
# Dropo rows with missing education levels
df = df.dropna(subset=['Education_Level'])

In [221]:
df

,Patient_ID,Age,Gender,Smoking_Status,Hypertension,Diabetes,Obesity,Cholesterol_Level,Air_Pollution_Exposure,Physical_Activity,Diet_Score,Stress_Level,Alcohol_Consumption,Family_History_CVD,Healthcare_Access,Rural_or_Urban,Region,Province,Hospital_Availability,TCM_Use,Employment_Status,Education_Level,Income_Level,Blood_Pressure,Chronic_Kidney_Disease,Previous_Heart_Attack,CVD_Risk_Score,Heart_Attack
0,1,55,Male,Non-Smoker,No,No,Yes,Normal,High,High,Moderate,Low,Yes,No,Good,Rural,Eastern,Beijing,Low,Yes,Unemployed,Primary,Low,104,Yes,No,78,No
1,2,66,Female,Smoker,Yes,No,No,Low,Medium,High,Healthy,Medium,No,Yes,Poor,Urban,Eastern,Qinghai,High,No,Unemployed,Secondary,Middle,142,No,No,49,No
2,3,69,Female,Smoker,No,No,No,Low,Medium,High,Moderate,Low,No,No,Poor,Rural,Eastern,Henan,Low,No,Unemployed,Primary,High,176,No,No,31,No
3,4,45,Female,Smoker,No,Yes,No,Normal,Medium,Low,Healthy,Medium,Yes,No,Poor,Rural,Central,Qinghai,Medium,Yes,Employed,Primary,Low,178,No,Yes,23,No
4,5,39,Female,Smoker,No,No,No,Normal,Medium,Medium,Healthy,Low,No,No,Moderate,Urban,Western,Guangdong,Low,No,Retired,Higher,Middle,146,Yes,No,79,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239261,239262,53,Male,Non-Smoker,No,No,No,Normal,Medium,Medium,Healthy,Medium,No,No,Moderate,Urban,Northern,Henan,High,Yes,Retired,Higher,Low,167,No,No,86,Yes
239262,239263,48,Female,Non-Smoker,No,No,Yes,Normal,Low,Medium,Poor,High,No,No,Poor,Rural,Western,Shanghai,Medium,Yes,Unemployed,Higher,Low,179,No,No,25,No
239263,239264,57,Male,Smoker,Yes,No,No,Normal,Low,High,Poor,Low,No,No,Moderate,Urban,Southern,Gansu,Medium,Yes,Retired,Higher,Middle,136,No,No,89,No
239264,239265,42,Female,Non-Smoker,No,No,No,High,Medium,High,Poor,High,No,Yes,Poor,Rural,Southern,Sichuan,Low,Yes,Employed,Primary,Middle,159,No,No,72,Yes
239265,239266,79,Male,Non-Smoker,No,No,No,High,Medium,Medium,Moderate,Medium,No,No,Poor,Urban,Southern,Henan,High,No,Retired,Secondary,Low,112,Yes,No,46,No

In [209]:
#Find duplicates
df.duplicated().sum()

0

In [211]:
# Cleaning outliers for genres dataset
def filter_outliers(df1, columns):
    for col in columns:
        q1 = df[col]. quantile(0.25)
        q3 = df[col]. quantile(0.75)
        iqr = q3 - q1
        print(f"IQR for {col}: {iqr}")
        lower_bound = q1 - 1.5 *iqr
        upper_bound = q3 + 1.5 *iqr
        df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound) ]
    return df

,Patient_ID,Age,Gender,Smoking_Status,Hypertension,Diabetes,Obesity,Cholesterol_Level,Air_Pollution_Exposure,Physical_Activity,Diet_Score,Stress_Level,Alcohol_Consumption,Family_History_CVD,Healthcare_Access,Rural_or_Urban,Region,Province,Hospital_Availability,TCM_Use,Employment_Status,Education_Level,Income_Level,Blood_Pressure,Chronic_Kidney_Disease,Previous_Heart_Attack,CVD_Risk_Score,Heart_Attack
0,1,55,Male,Non-Smoker,No,No,Yes,Normal,High,High,Moderate,Low,Yes,No,Good,Rural,Eastern,Beijing,Low,Yes,Unemployed,Primary,Low,104,Yes,No,78,No
1,2,66,Female,Smoker,Yes,No,No,Low,Medium,High,Healthy,Medium,No,Yes,Poor,Urban,Eastern,Qinghai,High,No,Unemployed,Secondary,Middle,142,No,No,49,No
2,3,69,Female,Smoker,No,No,No,Low,Medium,High,Moderate,Low,No,No,Poor,Rural,Eastern,Henan,Low,No,Unemployed,Primary,High,176,No,No,31,No
3,4,45,Female,Smoker,No,Yes,No,Normal,Medium,Low,Healthy,Medium,Yes,No,Poor,Rural,Central,Qinghai,Medium,Yes,Employed,Primary,Low,178,No,Yes,23,No
4,5,39,Female,Smoker,No,No,No,Normal,Medium,Medium,Healthy,Low,No,No,Moderate,Urban,Western,Guangdong,Low,No,Retired,Higher,Middle,146,Yes,No,79,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239261,239262,53,Male,Non-Smoker,No,No,No,Normal,Medium,Medium,Healthy,Medium,No,No,Moderate,Urban,Northern,Henan,High,Yes,Retired,Higher,Low,167,No,No,86,Yes
239262,239263,48,Female,Non-Smoker,No,No,Yes,Normal,Low,Medium,Poor,High,No,No,Poor,Rural,Western,Shanghai,Medium,Yes,Unemployed,Higher,Low,179,No,No,25,No
239263,239264,57,Male,Smoker,Yes,No,No,Normal,Low,High,Poor,Low,No,No,Moderate,Urban,Southern,Gansu,Medium,Yes,Retired,Higher,Middle,136,No,No,89,No
239264,239265,42,Female,Non-Smoker,No,No,No,High,Medium,High,Poor,High,No,Yes,Poor,Rural,Southern,Sichuan,Low,Yes,Employed,Primary,Middle,159,No,No,72,Yes
239265,239266,79,Male,Non-Smoker,No,No,No,High,Medium,Medium,Moderate,Medium,No,No,Poor,Urban,Southern,Henan,High,No,Retired,Secondary,Low,112,Yes,No,46,No

In [184]:
# Unique values of the chloesterol column
df['Cholesterol_Level'].unique()

array(['Normal', 'Low', 'High'], dtype=object)

In [186]:
df['Blood_Pressure'].mean()

134.53168122282895

In [188]:
df['Previous_Heart_Attack'].value_counts()

Previous_Heart_Attack
No     161695
Yes     17954
Name: count, dtype: int64

In [190]:
df = df['Heart_Attack'] == 'Yes'

In [196]:
df

0         False
1         False
2         False
3         False
4         False
          ...
239261     True
239262    False
239263    False
239264     True
239265    False
Name: Heart_Attack, Length: 179649, dtype: bool

In [227]:
df.to_csv('China_heartattack_data_')

In [116]:
# Database connection details
USERNAME = "docker"
PASSWORD = "1234"  # Replace with your actual password
HOST = "localhost"  # PostgreSQL is running locally
PORT = "5432"
DATABASE = "docker"  # Database name

# Create the SQLAlchemy engine
engine = create_engine(f"postgresql://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}")

# Write DataFrame to PostgreSQL (append data to existing table)
df.to_sql("ChinaHealthData", engine, if_exists="append", index=False)

print("✅ CSV data successfully loaded into 'ChinaHealthData' table!")

✅ CSV data successfully loaded into 'ChinaHealthData' table!

In [118]:
df.describe()

          Patient_ID            Age  Blood_Pressure  CVD_Risk_Score
count  179649.000000  179649.000000   179649.000000   179649.000000
mean   119522.933643      59.457297      134.531681       54.478583
std     69053.954462      17.342695       25.970187       25.956060
min         1.000000      30.000000       90.000000       10.000000
25%     59638.000000      44.000000      112.000000       32.000000
50%    119570.000000      59.000000      135.000000       54.000000
75%    179318.000000      74.000000      157.000000       77.000000
max    239266.000000      89.000000      179.000000       99.000000

In [122]:
#Select numeric values from dataset
numeric_df = df.select_dtypes(include=[float, int])

In [126]:
correlation_matrix = numeric_df.corr(method='kendall')
correlation_matrix

                Patient_ID       Age  Blood_Pressure  CVD_Risk_Score
Patient_ID        1.000000  0.000784       -0.000248       -0.000871
Age               0.000784  1.000000        0.000870       -0.000657
Blood_Pressure   -0.000248  0.000870        1.000000        0.004141
CVD_Risk_Score   -0.000871 -0.000657        0.004141        1.000000

In [241]:
df_heart = df['Heart_Attack']=='Yes'
df_heart.value_counts()

Heart_Attack
False    157792
True      21857
Name: count, dtype: int64